SELECT * FROM EMPLOYEE

CREATE TABLE PERSON(
ID INT,
NAME NVARCHAR(19),
LOCATION NVARCHAR(20));

SELECT * FROM PERSON

ALTER TABLE PERSON
ADD NUMBER INT;

ALTER TABLE EMPLOYEE
DROP COLUMN LOCATION;

DROP TABLE PERSON;

TRUNCATE TABLE PERSON;