SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;

SELECT NAME,GENDER,SALARY,DEPARTMENTNAME
FROM EMPLOYEE 
INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.ID;

SELECT NAME,GENDER,SALARY,DEPARTMENTNAME
FROM EMPLOYEE 
LEFT OUTER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.ID;

SELECT NAME,GENDER,SALARY,DEPARTMENTNAME
FROM EMPLOYEE 
RIGHT OUTER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.ID;

SELECT NAME,GENDER,SALARY,DEPARTMENTNAME
FROM EMPLOYEE 
FULL OUTER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.ID;

SELECT NAME,GENDER,SALARY,DEPARTMENTNAME
FROM EMPLOYEE 
CROSS JOIN DEPARTMENT






