
SELECT NAME,GENDER FROM EMPLOYEE

CREATE PROCEDURE SPGETEMPLOYEE
AS
BEGIN
     SELECT NAME,GENDER FROM EMPLOYEE
END

SPGETEMPLOYEE

CREATE PROC SPGETEMPLOYESBYGENDERANDDEPARTMENT
@GENDER NVARCHAR(20),
@DEPARTMENTID INT
AS
BEGIN
     SELECT NAME,GENDER,DEPARTMENTID FROM EMPLOYEE WHERE GENDER=@GENDER
	 AND DEPARTMENTID=@DEPARTMENTID
END

SPGETEMPLOYESBYGENDERANDDEPARTMENT 'MALE',1
